// Strategy toggles – ALL ENABLED
STRATEGY_LP_ENABLED: optionalBool('STRATEGY_LP_ENABLED', true),
STRATEGY_VAULT_ENABLED: optionalBool('STRATEGY_VAULT_ENABLED', true),
STRATEGY_DEBT_ENABLED: optionalBool('STRATEGY_DEBT_ENABLED', true),
STRATEGY_HARVEST_ENABLED: optionalBool('STRATEGY_HARVEST_ENABLED', true),
STRATEGY_CLASSIC_ENABLED: optionalBool('STRATEGY_CLASSIC_ENABLED', true),